<?php
/**
 * Zoom Functions file
 * Calls all other required files
 * PLEASE DO NOT EDIT THIS FILE IN ANY WAY!
 *
 * @package Zoom
 * @since 1.0
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

//Loading support files
require get_template_directory() . '/inc/theme-init.php';